spring.application.name=skybooker-backend

spring.datasource.url=jdbc:mysql://localhost:3306/skybooker_db
spring.datasource.username=root
spring.datasource.password=root4545

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8585